# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - uses: pkg-src/github-action-git-bash@v1.1
    - name: Bundle
      run: |
        npm i
        gulp bundle
    - name: Commit files
      run: |
        git config --global user.name 'JakeSCahill'
        git config --global user.email '45230295+JakeSCahill@users.noreply.github.com'
        git add -f build
        git commit -m "Bundle UI"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BUNDLE }}
        branch: master
        repository: JakeSCahill/docs-poc
